from io import BytesIO
from PIL import Image

def flatten_alpha_to_white(img: Image.Image) -> Image.Image:
    if img.mode in ("RGBA", "LA") or ("transparency" in img.info):
        bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
        return Image.alpha_composite(bg, img.convert("RGBA")).convert("RGB")
    return img

def to_1bit_threshold(img: Image.Image, threshold: int) -> Image.Image:
    g = img.convert("L")
    # 1-bit: 0=black, 255=white
    return g.point(lambda p: 255 if p >= threshold else 0, mode="1")

def write_pbm_ascii_p1(img_1bit: Image.Image) -> bytes:
    """
    Write ASCII PBM (P1).
    PBM P1 uses ASCII '1' for black and '0' for white.
    """
    if img_1bit.mode != "1":
        raise ValueError("Image must be mode '1' to write PBM P1.")
    w, h = img_1bit.size
    lines = ["P1", "# Generated by PBM Sprite Editor (web)", f"{w} {h}"]
    px = img_1bit.load()
    for y in range(h):
        row_bits = []
        for x in range(w):
            bit = "1" if px[x, y] == 0 else "0"  # P1: 1=black, 0=white
            row_bits.append(bit)
        lines.append(" ".join(row_bits))
    text = "\n".join(lines) + "\n"
    return text.encode("ascii")

def image_to_png_bytes(img: Image.Image) -> bytes:
    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()
